### ISSUE TITLE
Opened file is not saved to original location

### ISSUE THREAD

**Issue by rudidlo** [rezabazargan/xDav#1]
I installed xDav via NuGet package manager into empty ASP.Net application. for opening files it works, but when I try to save document changes, Word shows me directory where I saved last document.

**Comment by bagherani** [comment]
> I installed xDav via NuGet package manager into empty ASP.Net application. for opening files it works, but when I try to save document changes, Word shows me directory where I saved last document.

Downgrading to `1.0.2` may helps.

**Comment by rudidlo** [comment]
I look at the xDav implementation and found that it is just library written over Sphorium, which is not completely implemented. Finally I've written my own implementation influenced by Sphorium.
