### ISSUE TITLE
Example application does not work

### ISSUE THREAD

**Issue by rudidlo** [rezabazargan/xDav#2]
I downloaded latest sources and tried to run example application. When I execute application, select Read me document and click on "Edit In Word" button, I get System.Invalidoperationexception in XDavFile constructor , because property FileName in XDavHelper.FileWrapper class is an empty string.

**Comment by rezabazargan** [comment]
thanks and sorry.
I've checked the code and found the option method some times doesn't have any filename, 
so fixed
